insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (1, 37, 14, 'Counterfeit item', 'Resolved', '9/17/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (2, 17, 16, 'Counterfeit item', 'Under Review', '1/27/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (3, 27, 25, 'Counterfeit item', 'Dismissed', '11/3/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (4, 49, 2, 'suspicious activity', 'Under Review', '10/17/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (5, 14, 26, 'Misleading description', 'Resolved', '2/27/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (6, 3, 14, 'scam attempt', 'Dismissed', '9/3/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (7, 19, 10, 'Counterfeit item', 'Dismissed', '10/31/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (8, 20, 24, 'Counterfeit item', 'Under Review', '1/25/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (9, 29, 28, 'other', 'Dismissed', '3/2/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (10, 9, 21, 'other', 'Under Review', '9/18/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (11, 9, 5, 'other', 'Dismissed', '4/29/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (12, 12, 26, 'Misleading description', 'Resolved', '6/17/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (13, 24, 7, 'other', 'Under Review', '1/28/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (14, 18, 23, 'Counterfeit item', 'Dismissed', '6/30/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (15, 21, 30, 'Item not as described', 'Dismissed', '5/24/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (16, 7, 20, 'other', 'Resolved', '10/22/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (17, 46, 26, 'other', 'Dismissed', '9/17/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (18, 21, 6, 'scam attempt', 'Dismissed', '8/6/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (19, 46, 5, 'Counterfeit item', 'Resolved', '9/16/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (20, 34, 22, 'suspicious activity', 'Dismissed', '7/22/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (21, 18, 10, 'Misleading description', 'Under Review', '9/10/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (22, 5, 27, 'Item not as described', 'Resolved', '3/20/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (23, 23, 21, 'Item not as described', 'Dismissed', '6/10/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (24, 9, 22, 'Counterfeit item', 'Resolved', '4/1/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (25, 48, 22, 'scam attempt', 'Dismissed', '5/2/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (26, 5, 20, 'Misleading description', 'Dismissed', '7/21/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (27, 33, 22, 'Counterfeit item', 'Dismissed', '2/3/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (28, 1, 26, 'Counterfeit item', 'Under Review', '6/1/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (29, 5, 12, 'Misleading description', 'Resolved', '7/9/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (30, 44, 26, 'suspicious activity', 'Dismissed', '2/12/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (31, 39, 27, 'Item not as described', 'Resolved', '7/25/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (32, 32, 5, 'scam attempt', 'Dismissed', '7/20/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (33, 22, 18, 'Item not as described', 'Resolved', '1/10/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (34, 5, 8, 'other', 'Dismissed', '8/12/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (35, 22, 26, 'scam attempt', 'Dismissed', '2/18/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (36, 29, 13, 'Misleading description', 'Under Review', '9/30/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (37, 44, 19, 'suspicious activity', 'Under Review', '9/11/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (38, 44, 4, 'Item not as described', 'Resolved', '6/17/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (39, 34, 7, 'suspicious activity', 'Dismissed', '9/14/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (40, 6, 3, 'scam attempt', 'Resolved', '8/7/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (41, 25, 29, 'suspicious activity', 'Dismissed', '11/29/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (42, 43, 13, 'Misleading description', 'Dismissed', '10/20/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (43, 21, 28, 'other', 'Under Review', '1/13/2025');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (44, 14, 6, 'Item not as described', 'Under Review', '6/28/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (45, 43, 5, 'other', 'Dismissed', '11/29/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (46, 20, 23, 'suspicious activity', 'Dismissed', '11/29/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (47, 24, 25, 'other', 'Under Review', '8/4/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (48, 36, 3, 'Item not as described', 'Under Review', '11/14/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (49, 6, 4, 'Item not as described', 'Dismissed', '12/3/2024');
insert into Fraud_Reports (report_id, trade_id, reported_by, reason, status, created_at) values (50, 45, 29, 'Misleading description', 'Resolved', '9/6/2024');
